name: Deploy dbt docs to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.8

    - name: Install dbt
      run: pip install dbt-core dbt-bigquery

    - name: Decode and save keyfile
      run: |
        mkdir -p ~/.dbt
        echo "${{ secrets.DBT_KEYFILE_PATH }}" | base64 --decode > ~/.dbt/keyfile.json

    - name: Export Environment Variables
      run: |
        echo "DBT_METHOD=${{ secrets.DBT_METHOD }}" >> $GITHUB_ENV
        echo "DBT_PROJECT=${{ secrets.DBT_PROJECT }}" >> $GITHUB_ENV
        echo "DBT_DATASET=${{ secrets.DBT_DATASET }}" >> $GITHUB_ENV
        echo "DBT_THREADS=${{ secrets.DBT_THREADS }}" >> $GITHUB_ENV
        echo "DBT_JOB_TIMEOUT=${{ secrets.DBT_JOB_TIMEOUT }}" >> $GITHUB_ENV
        echo "DBT_LOCATION=${{ secrets.DBT_LOCATION }}" >> $GITHUB_ENV
        echo "DBT_PRIORITY=${{ secrets.DBT_PRIORITY }}" >> $GITHUB_ENV
        echo "DBT_JOB_RETRIES=${{ secrets.DBT_JOB_RETRIES }}" >> $GITHUB_ENV
        echo "DBT_KEYFILE_PATH=${{ secrets.DBT_KEYFILE_PATH }}" >> $GITHUB_ENV

    - name: Set up dbt profile
      run: |
        cat <<EOF > ~/.dbt/profiles.yml
        softdrink_grocery:
          target: prod
          outputs:
            prod:
                type: bigquery
                project: ${{ secrets.DBT_PROJECT }}
                dataset: ${{ secrets.DBT_DATASET }}
                 keyfile: ~/.dbt/keyfile.json
                location: ${{ secrets.DBT_LOCATION }}
                method: ${{ secrets.DBT_METHOD }}
                priority: ${{ secrets.DBT_PRIORITY }}
                threads: ${{ secrets.DBT_THREADS }}
                timeout: ${{ secrets.DBT_JOB_TIMEOUT }}
                retries: ${{ secrets.DBT_JOB_RETRIES }}
        EOF

    - name: Install dependencies and generate docs
      run: |
        dbt docs generate

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GH_PAT }}
        publish_dir: ./target
